name: open_meteo_api_client
description: A Dart API Client for the Open-Meteo API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  dio: ^5.3.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.3

dev_dependencies:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.3
