include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_untyped_parameter: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
