name: super_weather
description: Super weather.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  bloc: ^8.1.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  rxdart: ^0.27.7
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  open_meteo_api_client:
    path: packages/open_meteo_api_client
  geocoding_repository:
    path: packages/geocoding_repository
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
