name: super_weather
description: Super weather.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  build_runner: any
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
