name: weather_repository
description: A Dart Repository which manages the weather domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  open_meteo_api_client:
    path: ../open_meteo_api_client

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  mocktail: ^1.0.0
